# Generated by Django 4.1.1 on 2022-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="product_link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
