# Generated by Django 4.1.1 on 2022-09-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_products_product_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Products",
        ),
    ]
