# Generated by Django 4.1.1 on 2022-09-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
