# Generated by Django 4.1.1 on 2022-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(default=1, upload_to="media/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
