# Generated by Django 4.1.1 on 2022-09-28 16:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_category_image_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=ckeditor.fields.RichTextField(default="descripton"),
        ),
    ]
