# Generated by Django 4.1.1 on 2022-09-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_products_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(default="descripton"),
        ),
    ]
